name: Lint

on:
  - push
  - pull_request

jobs:
  build:
   runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.8.10]
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python
    uses: actions/setup-python@v2
    with:
    python-version: ${{ matrix.python-version }}
    - name: Install dependencies
    run: |
      pip install poetry
      make install
  - name: Run linter and pytest
  run: |
    make check
